### ISSUE TITLE
Extraction error. They remain in empty folders

### ISSUE THREAD

**Issue by mario50245** [sk-zk/Extractor#12] opened 2024-09-12 02:29 UTC
Hello good evening

another error detected in fix 02-09 

It does not extract the files. When applying the '-p=/def' example, it extracts the folder but they are all empty. I attach evidence

![image](https://github.com/user-attachments/assets/965f222c-4276-41a3-8b93-954b053652aa)
 

and here the error does not show anything, the folder is empty

![image](https://github.com/user-attachments/assets/e54180c2-1672-4c17-b653-299cbca3f7ff)
 
but in version 07-15-2024 it is extracted without any problem. 
It happens with mods of version 1.51

**Comment by sk-zk** [comment] 2024-09-12 10:56
Gonna need a link to the mod, as usual

**Comment by mario50245** [comment] 2024-09-13 03:34
https://drive.google.com/file/d/1TQhv52SK6jYI_jXiaABHsmlgMJt8XtkM/view?usp=sharing

**Comment by sk-zk** [comment] 2024-09-15 14:10
Hmm, I'm unable to reproduce this. Here's what I get:

<img src="https://i.imgur.com/uvoTLey.png" width=500>

Can you double-check you're running the latest version (maybe there's an old version in PATH?) and that there's no antivirus running that could be interfering with it?

**Comment by mario50245** [comment] 2024-09-15 20:20
I took another bus and the same problem continues but with version 15-07 I have no problems, it's only with version 02-09

![image](https://github.com/user-attachments/assets/0962e3d2-2e33-4b40-a97e-41ca1b522c41)

![image](https://github.com/user-attachments/assets/5509d695-7e21-4772-9713-c6900a5938e9)

**Comment by mario50245** [comment] 2024-09-15 20:31
And another problem that I detected is that in a map in version 1.51 it leaves the files with errors and the map ends up closing


I unlocked it folder by folder but when I started it I got to use it and it closed

**Comment by sk-zk** [comment] 2024-09-15 21:07
OK, I can repro the bug now - it only happens if `-d` gets an absolute path. I'll take a look at this tomorrow

**Comment by sk-zk** [comment] 2024-09-16 12:41
Fixed in 2024-09-16

**Closed by sk-zk** 2024-09-16 12:41 UTC
Labels: bug

**Comment by n4vi98** [comment] 2024-09-23 12:52
> Fixed in 2024-09-16

ty for the update, this now works with Cvault again 😁
